package com.example.ui

import androidx.compose.ui.graphics.Color

object ThemeData {
    val ALL_THEMES: List<AppTheme> = listOf(
        // ── 10 CURATED DARK THEMES ──────────────────────────────
        AppTheme("matte_black", "Matte Black", isDark = true, background = Color(0xFF060606), card = Color(0xFF111111), primary = Color(0xFFFFFFFF), border = Color(0xFF202020), textPrimary = Color.White, textSecondary = Color.Gray, category = "dark"),
        AppTheme("nord", "Nord Frost", isDark = true, background = Color(0xFF2E3440), card = Color(0xFF3B4252), primary = Color(0xFF88C0D0), border = Color(0xFF434C5E), textPrimary = Color(0xFFECEFF4), textSecondary = Color(0xFF9099AB), category = "dark"),
        AppTheme("monokai", "Monokai Pro", isDark = true, background = Color(0xFF272822), card = Color(0xFF3E3D32), primary = Color(0xFFE6DB74), border = Color(0xFF49483E), textPrimary = Color(0xFFF8F8F2), textSecondary = Color(0xFF75715E), category = "dark"),
        AppTheme("catppuccin", "Catppuccin Mocha", isDark = true, background = Color(0xFF1E1E2E), card = Color(0xFF313244), primary = Color(0xFFCBA6F7), border = Color(0xFF45475A), textPrimary = Color(0xFFCDD6F4), textSecondary = Color(0xFF6C7086), category = "dark"),
        AppTheme("dracula", "Dracula Night", isDark = true, background = Color(0xFF282A36), card = Color(0xFF343746), primary = Color(0xFFBD93F9), border = Color(0xFF44475A), textPrimary = Color(0xFFF8F8F2), textSecondary = Color(0xFF6272A4), category = "dark"),
        AppTheme("gruvbox_dark", "Gruvbox Dark", isDark = true, background = Color(0xFF282828), card = Color(0xFF3C3836), primary = Color(0xFFD79921), border = Color(0xFF504945), textPrimary = Color(0xFFEBDBB2), textSecondary = Color(0xFF928374), category = "dark"),
        AppTheme("material", "Material Midnight", isDark = true, background = Color(0xFF121212), card = Color(0xFF1E1E1E), primary = Color(0xFF03DAC6), border = Color(0xFF2C2C2C), textPrimary = Color(0xFFFFFFFF), textSecondary = Color(0xFF808080), category = "dark"),
        AppTheme("vscode", "VS Code Dark", isDark = true, background = Color(0xFF1E1E1E), card = Color(0xFF252526), primary = Color(0xFF569CD6), border = Color(0xFF3E3E42), textPrimary = Color(0xFFD4D4D4), textSecondary = Color(0xFF808080), category = "dark"),
        AppTheme("aurora", "Aurora Borealis", isDark = true, background = Color(0xFF0D1117), card = Color(0xFF161B22), primary = Color(0xFF79C0FF), border = Color(0xFF30363D), textPrimary = Color(0xFFE6EDF3), textSecondary = Color(0xFF8B949E), category = "dark"),
        AppTheme("moonlight", "Moonlight Deep", isDark = true, background = Color(0xFF1B1D2B), card = Color(0xFF222436), primary = Color(0xFF82AAFF), border = Color(0xFF2F334D), textPrimary = Color(0xFFC8D3F5), textSecondary = Color(0xFF636DA6), category = "dark"),

        // ── 10 CURATED LIGHT THEMES ─────────────────────────────
        AppTheme("creampie", "Vanilla Cream", isDark = false, background = Color(0xFFFDF6EC), card = Color(0xFFFEEFE3), primary = Color(0xFFE8789A), border = Color(0xFFEDD5C8), textPrimary = Color(0xFF3A2030), textSecondary = Color(0xFFAA8090), category = "light"),
        AppTheme("macintosh", "Classic Mac", isDark = false, background = Color(0xFFEEEEEE), card = Color(0xFFFFFFFF), primary = Color(0xFF000000), border = Color(0xFF888888), textPrimary = Color(0xFF000000), textSecondary = Color(0xFF555555), category = "light"),
        AppTheme("nordic_frost_light", "Nordic Frost", isDark = false, background = Color(0xFFF1F5F9), card = Color(0xFFFFFFFF), primary = Color(0xFF2563EB), border = Color(0xFFE2E8F0), textPrimary = Color(0xFF1E293B), textSecondary = Color(0xFF64748B), category = "light"),
        AppTheme("paper", "Warm Paper", isDark = false, background = Color(0xFFF5F0E8), card = Color(0xFFEDE7D9), primary = Color(0xFF5C4A2A), border = Color(0xFFD4C9B0), textPrimary = Color(0xFF2C2418), textSecondary = Color(0xFF8C7B5A), category = "light"),
        AppTheme("slambook", "Sunset Coral", isDark = false, background = Color(0xFFFFF8F0), card = Color(0xFFFFF0E0), primary = Color(0xFFE8622A), border = Color(0xFFE8D5B0), textPrimary = Color(0xFF3A2010), textSecondary = Color(0xFFA07850), category = "light"),
        AppTheme("camping", "Forest Sage", isDark = false, background = Color(0xFFF0EDE4), card = Color(0xFFE8E0D0), primary = Color(0xFF6B7C3E), border = Color(0xFFCCC4A8), textPrimary = Color(0xFF2A2E1A), textSecondary = Color(0xFF7A8060), category = "light"),
        AppTheme("blueberry_light", "Soft Blueberry", isDark = false, background = Color(0xFFF0F0FF), card = Color(0xFFE8E8FF), primary = Color(0xFF4A4AE8), border = Color(0xFFCCCCFF), textPrimary = Color(0xFF1A1A4A), textSecondary = Color(0xFF6A6AAA), category = "light"),
        AppTheme("lavender", "Lavender Mist", isDark = false, background = Color(0xFFF8F4FF), card = Color(0xFFF0EAFF), primary = Color(0xFF7C5CBF), border = Color(0xFFDDD0F5), textPrimary = Color(0xFF2A1A4A), textSecondary = Color(0xFF8A72AA), category = "light"),
        AppTheme("breeze", "Sky Breeze", isDark = false, background = Color(0xFFF0F8FF), card = Color(0xFFE8F4FF), primary = Color(0xFF2E86C1), border = Color(0xFFBDD7EE), textPrimary = Color(0xFF0A2A44), textSecondary = Color(0xFF5A8EAA), category = "light"),
        AppTheme("peaches", "Sweet Peach", isDark = false, background = Color(0xFFFFF5F0), card = Color(0xFFFFEDE5), primary = Color(0xFFE8724A), border = Color(0xFFFFCDB8), textPrimary = Color(0xFF3A1A0A), textSecondary = Color(0xFFAA6A50), category = "light"),

        // ── SPECIAL & VIP SUPPORTER AESTHETIC THEMES ───────────
        AppTheme("revolutionary", "Revolutionary Red ★", isDark = true, background = Color(0xFF131311), card = Color(0xFF1C1C19), primary = Color(0xFFC32021), border = Color(0xFF2E2C29), textPrimary = Color(0xFFEBE4D3), textSecondary = Color(0xFF88847C), category = "special", isSupporterOnly = true),
        AppTheme("revolutionary_cream", "Revolutionary Cream ★", isDark = false, background = Color(0xFFEBE4D3), card = Color(0xFFDFD7C7), primary = Color(0xFFC32021), border = Color(0xFF2E2C29), textPrimary = Color(0xFF131311), textSecondary = Color(0xFF5A5752), category = "special", isSupporterOnly = true),
        AppTheme("matrix", "Matrix Terminal ★", isDark = true, background = Color(0xFF000000), card = Color(0xFF0A0F0A), primary = Color(0xFF00FF41), border = Color(0xFF003B00), textPrimary = Color(0xFF00FF41), textSecondary = Color(0xFF007A1F), category = "special", isSupporterOnly = true),
        AppTheme("future_funk", "Future Funk Synth ★", isDark = true, background = Color(0xFF0F0F1A), card = Color(0xFF1A1A2E), primary = Color(0xFFFF6EC7), border = Color(0xFF2A2A45), textPrimary = Color(0xFFFFE0F5), textSecondary = Color(0xFF9966AA), category = "special", isSupporterOnly = true),
        AppTheme("vhs", "Retro VHS 80s ★", isDark = true, background = Color(0xFF0D0D0D), card = Color(0xFF1A1A1A), primary = Color(0xFFFF2D78), border = Color(0xFF2A0A14), textPrimary = Color(0xFFFFE0EC), textSecondary = Color(0xFF884455), category = "special", isSupporterOnly = true),
        AppTheme("arcade", "Neon Arcade ★", isDark = true, background = Color(0xFF080818), card = Color(0xFF100E28), primary = Color(0xFFFFE600), border = Color(0xFF1E1A40), textPrimary = Color(0xFFFFFFCC), textSecondary = Color(0xFF8888AA), category = "special", isSupporterOnly = true),
        AppTheme("phosphor", "Phosphor CRT ★", isDark = true, background = Color(0xFF060E06), card = Color(0xFF0C180C), primary = Color(0xFF33FF33), border = Color(0xFF143014), textPrimary = Color(0xFFCCFFCC), textSecondary = Color(0xFF448844), category = "special", isSupporterOnly = true),
        AppTheme("red_samurai", "Red Samurai ★", isDark = true, background = Color(0xFF110A0A), card = Color(0xFF1C1010), primary = Color(0xFFCC2936), border = Color(0xFF3A1515), textPrimary = Color(0xFFF0D0D0), textSecondary = Color(0xFF8C5555), category = "special", isSupporterOnly = true),
        AppTheme("royal_gold_vip", "Royal 24K Gold VIP", isDark = true, background = Color(0xFF0A0905), card = Color(0xFF18150A), primary = Color(0xFFFFD700), border = Color(0xFF423714), textPrimary = Color(0xFFFFF6D6), textSecondary = Color(0xFFA6935C), category = "special", isSupporterOnly = true),
        AppTheme("nebula_opal_vip", "Nebula Hologram VIP", isDark = true, background = Color(0xFF0B0A18), card = Color(0xFF16142E), primary = Color(0xFF00E5FF), border = Color(0xFF382D6E), textPrimary = Color(0xFFF0EAFF), textSecondary = Color(0xFF9E8CD0), category = "special", isSupporterOnly = true),
        AppTheme("emerald_elite_vip", "Emerald Elite VIP", isDark = true, background = Color(0xFF05100B), card = Color(0xFF0C1F16), primary = Color(0xFF00E676), border = Color(0xFF1B4D36), textPrimary = Color(0xFFE0F7ED), textSecondary = Color(0xFF6EAA8E), category = "special", isSupporterOnly = true),
        AppTheme("rose_diamond_vip", "Rose Diamond VIP", isDark = false, background = Color(0xFFFFF0F5), card = Color(0xFFFFE4EE), primary = Color(0xFFFF1493), border = Color(0xFFF5B6CD), textPrimary = Color(0xFF4A0E2E), textSecondary = Color(0xFFAA4B7B), category = "special", isSupporterOnly = true),
        AppTheme("sunset_velvet_vip", "Sunset Velvet VIP", isDark = true, background = Color(0xFF14081E), card = Color(0xFF220E33), primary = Color(0xFFFF6D00), border = Color(0xFF4D1A6B), textPrimary = Color(0xFFFFEBE5), textSecondary = Color(0xFFB373A1), category = "special", isSupporterOnly = true),
        AppTheme("cyber_obsidian_vip", "Cyber Obsidian VIP", isDark = true, background = Color(0xFF05070A), card = Color(0xFF0C111A), primary = Color(0xFF00F0FF), border = Color(0xFF16273B), textPrimary = Color(0xFFE2F3FD), textSecondary = Color(0xFF5D7B99), category = "special", isSupporterOnly = true)
    )
}
